### PR TITLE
opus and zrtp

### PR DESCRIPTION
**Pull request by juha-h**
added opus and zrtp modules (optional)

### CODE REVIEW

**Comment by alfredh** [comment]
this works a bit better, now it fails on the `make` step:

```
make[1]: Entering directory '/home/alfredh/git/baresip-android/opus'
make  all-recursive
make[2]: Entering directory '/home/alfredh/git/baresip-android/opus'
make[3]: Entering directory '/home/alfredh/git/baresip-android/opus'
  CC       celt/bands.lo
./libtool: line 1749: arm-linux-androideabi-gcc: command not found
Makefile:2281: recipe for target 'celt/bands.lo' failed
make[3]: *** [celt/bands.lo] Error 1
make[3]: Leaving directory '/home/alfredh/git/baresip-android/opus'
Makefile:2379: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/alfredh/git/baresip-android/opus'
Makefile:1396: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/alfredh/git/baresip-android/opus'
Makefile:143: recipe for target 'opus' failed
make: *** [opus] Error 2

```

this was fixed by adding PATH in front of make:

```
PATH=$(BIN):$(PATH) make &&
```

**Comment by alfredh** [comment]
make zrtp also fails with some errors.

one solution is to add some paths to the CFLAGS:

```
+       -I$(PWD)/libzrtp/third_party/bgaes \
+       -I$(PWD)/libzrtp/third_party/bnlib \
```

and the LFLAGS:

```
+       -L$(PWD)/libzrtp/third_party/bnlib \
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> make zrtp also fails with some errors.

i tried again and mine does not fail.  there is this in configure:

========================= configuring bnlib ==============================
checking For C compiler... arm-linux-androideabi-gcc --sysroot /usr/src/android/android-ndk-r13/platforms/android-17/arch-arm
checking whether we are using GNU CC... yes
checking for ranlib... /usr/src/android/android-ndk-r13/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/usr/src/baresip-android/libzrtp/third_party/bnlib':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.

but since there is --host in CC the error should not matter.

make generates lots of warnings, but it goes through.

i'm using the PR version that has this:

CFLAGS    := \
	-isystem $(SYSROOT)/usr/include/ \
	-I$(PWD)/openssl/include \
	-I$(PWD)/opus/include_opus \
	-I$(PWD)/libzrtp/include \
...

i have also tested zrtp call in my device and it works.

-- juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> this was fixed by adding PATH in front of make:
> 
> ```
> PATH=$(BIN):$(PATH) make &&

my new pull request should have the same.

-- juha

**Pull request closed without merging**
