### PR TITLE
opus and zrtp

### PR DESCRIPTION
**Pull request by juha-h**
added opus and zrtp modules (optional)

### CODE REVIEW

**Comment by alfredh** [comment]
many thanks :)

make opus does not work for me:

```
alfredh@debian:~/git/baresip-android$ make opus
cd opus && \
	rm -rf include_opus && \
	CC="arm-linux-androideabi-gcc --sysroot /home/alfredh/android/android-ndk-r13/platforms/android-17/arch-arm" \
	RANLIB=/home/alfredh/android/android-ndk-r13/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib AR=/home/alfredh/android/android-ndk-r13/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar \
	./configure --host=arm-linux-androideabi --disable-shared CFLAGS="-march=armv7-a" && \
	make && \
	mkdir include_opus && \
	mkdir include_opus/opus && \
	cp include/* include_opus/opus
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking how to print strings... printf
checking for style of include used by make... GNU
checking for arm-linux-androideabi-gcc... arm-linux-androideabi-gcc --sysroot /home/alfredh/android/android-ndk-r13/platforms/android-17/arch-arm
checking whether the C compiler works... no
configure: error: in `/home/alfredh/git/baresip-android/opus':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:143: recipe for target 'opus' failed
make: *** [opus] Error 77

```


the compiler `arm-linux-androideabi-gcc` is installed but is not in `$PATH`

**Comment by juha-h** [comment]
while making more tests, i noticed also this:

 CC       src/opus_decoder.lo
src/opus_decoder.c:37:10: note: #pragma message: You appear to be compiling without optimization, if so opus will be very slow.
 # pragma message "You appear to be compiling without optimization, if so opus will be very slow."
          ^
should more options be added on CC= line?

-- juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> make opus does not work for me:

sorry, too many copy/pastes.  path was missing:

RANLIB=$(RANLIB) AR=$(AR) PATH=$(BIN):$(PATH) \

i'll make more tests and then new PR.

-- juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> make opus does not work for me:

i added PATH to configure and replaced the pull request.

-- juha

**Pull request closed without merging**
